language: python
python:
- '3.6'
- '3.7'
install:
- pip install -r requirements.txt
script:
- python test.py
deploy:
  provider: pypi
  user: __token__
  password:
    secure: npKsrEli7G9wyj5PGA2cVAZOzeJ8GhxYvp31Y8/+F0ZeHfnycliiACuvDsMFp7TQY5FZk4+BC81Ud5BfFy8WUewi5EkkkKwxR9qJu3NtNrZpQDV8De/tU69a2E+8Dw9ivXECtjhHQ1ihlt0h4fLgFPUitO9rV0bh70XQU6VIraRQcl4OO+1m08xhiyXJMSS7gRDMN5bOyxzdVX8b9P2A10GGqDQzp/P8bjy/lIQbdr5rLXtomqVtltuNiUSmnzXvXOFNJWCMpsTqbjQf1Vmg1Rhn4lv4Vc6gt62HE/x1hvGCHyQBvoKY6XcLSOxcz37asT/d2Qrzn6sCAP138p/w85fIz0TM9RYFWU7h4NM1s9a3c0OwTslk3RjiQAY99Y107dQuooGYXmsz14FBnX8osyg5tbDslAD60JLSMr6W3fs2OGJtg16jQkKIDk2LpSAlGFpe5ZhnAGqTvs1p2M71dT3lJ24fb6ymNytxu1V2ow8XxgARa4QtDfdB8oazT7VtR9T/WNcTkLqT8+845pDmJu+l+StBttZvyJfVUAZ3d2Odzy+EWCbrlFJmrfbDA9vLAkW2yYg8WWOwAzbZ/lCnpbWCjw4DzLqy54tzriOZfx8X+apqXe4WzNy+kG2678f6HoV7KbSH1kctl3QG5EMixdu78vwhHpxYsevqcGjzuMo=
  on:
    tags: true
